server:
  port: 8888

spring:
  application:
    name: example
# ???? ??
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config

# server endpoint : localhost:8888/example/default
# server endpoint : localhost:8888/example/dev
# server endpoint : localhost:8888/example/prod

# public git ??
# git ??? ??? ?? ??? ??? application? name? file? ??? ???? ??.
# EX) {applicationName}-{env}.yml
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Leerilla/configFileRepo
# private ??? ??? ?? ??? ??? ???? ????? ??? ? ??? ???? ??? ssh ???? ???? ?? ????.
#          username:
#          password:

management:
  endpoints:
    web:
      exposure:
        include: ['refresh', 'beans', 'evn']



